### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by kmhari** [lak07/F22-Labs-test#1]
```
('Length of generated code is:', 7)
('Number of attempts allowed =', 3.0)
Enter Your Guess: ABCDEFG
Traceback (most recent call last):
  File "laksha.py", line 38, in <module>
    y=list(input("Enter Your Guess: ").upper())
  File "<string>", line 1, in <module>
NameError: name 'ABCDEFG' is not defined
```

**Comment by lak07** [comment]
Sir,
i have written this code in python 3 please run it using python 3.x.x. I guess you are using python2.x.x to run this program. This is error is because i am  using input() in python 3.x.x  instead of raw_input which is used in pyhton 2.x.x.
Thank You,
Lakshay Sharma

**Comment by lak07** [comment]
I have written this code in python 3 please run it using python 3
